### ISSUE TITLE
Old article doesn't redirect correctly

### ISSUE THREAD

**Issue by carlosperate** [ARMmbed/Handbook#1005]
# Docs issue template

## Page link

Original URL: https://docs.mbed.com/docs/mbed-os-handbook/en/5.4/debugging/debugging_microbit/

## Expected to find...

Should redirect to: https://os.mbed.com/docs/mbed-os/v5.11/tutorials/debug-microbit.html

## Found

Instead it redirects to: https://os.mbed.com/docs/mbed-os/v5.11/introduction/index.html

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-963*

**Comment by AnotherButler** [comment]
@JoeTheGuitarist I don't think I can fix this one. Could someone on your team please look into this?

**Comment by JoeTheGuitarist** [comment]
@AnotherButler yes, I'll add a ticket.

**Comment by AnotherButler** [comment]
Thanks 👍

**Comment by carlosperate** [comment]
Thanks @AnotherButler and @JoeTheGuitarist!

**Comment by AnotherButler** [comment]
@carlosperate Thanks for raising this issue. We've implemented redirects for documentation for Mbed OS 5.6 and later. We have no plans at this time to implement redirects for documentation before Mbed OS 5.6.
