### ISSUE TITLE
'mbed import' could not import from https://os.mbed.com

### ISSUE THREAD

**Issue by turmary** [ARMmbed/Handbook#1038]
# Docs issue template

## Found
tary@tary-think MINGW32 /f/home/tary/mbed
$ git clone https://os.mbed.com/users/hudakz/code/CAN_Hello
Cloning into 'CAN_Hello'...
fatal: unable to update url base from redirection:
  asked for: https://os.mbed.com/users/hudakz/code/CAN_Hello/info/refs?service=git-upload-pack
   redirect: https://os.mbed.com/users/hudakz/code/CAN_Hello/info/refs/?service=git-upload-pack

tary@tary-think MINGW32 /f/home/tary/mbed
$ git clone http://os.mbed.com/users/hudakz/code/CAN_Hello
Cloning into 'CAN_Hello'...
fatal: unable to update url base from redirection:
  asked for: http://os.mbed.com/users/hudakz/code/CAN_Hello/info/refs?service=git-upload-pack
   redirect: https://os.mbed.com/users/hudakz/code/CAN_Hello/info/refs/?service=git-upload-pack

tary@tary-think MINGW32 /f/home/tary/mbed
$ mbed import http://os.mbed.com/users/hudakz/code/CAN_Hello
[mbed] Working path "F:\home\tary\mbed" (directory)
[mbed] Program path "F:\home\tary\mbed"
[mbed] Importing program "CAN_Hello" from "https://os.mbed.com/users/hudakz/code/CAN_Hello" at latest revision in the current branch
[mbed] ERROR: Unable to clone repository (http://os.mbed.com/users/hudakz/code/CAN_Hello)

tary@tary-think MINGW32 /f/home/tary/mbed
$ mbed import https://os.mbed.com/users/hudakz/code/CAN_Hello
[mbed] Working path "F:\home\tary\mbed" (directory)
[mbed] Program path "F:\home\tary\mbed"
[mbed] Importing program "CAN_Hello" from "https://os.mbed.com/users/hudakz/code/CAN_Hello" at latest revision in the current branch
[mbed] ERROR: Unable to clone repository (https://os.mbed.com/users/hudakz/code/CAN_Hello)

**Comment by AnotherButler** [comment]
@SenRamakri Could someone from your team help with this?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-995*

**Comment by cmonr** [comment]
@turmary Please reopen this issue in Mbed OS: https://github.com/ARMmbed/mbed-os/

This does not appear to be a tool issue, not doc issue.
