### ISSUE TITLE
watchdog.h can not be found in source

### ISSUE THREAD

**Issue by lauri-piikivi** [ARMmbed/Handbook#1042]
## Page link
https://os.mbed.com/docs/mbed-os/v5.12/porting/watchdog-port.html

## Expected to find...
watchdog.h or any of the watchdog structures in the source

## Found
nothing

The below PR seems to say we deleted the watchdog.h from source version control, but helps remain
https://github.com/ARMmbed/mbed-os/pull/8801

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1006*
