### ISSUE TITLE
Connectivity configuration documentation is lost

### ISSUE THREAD

**Issue by SeppoTakalo** [ARMmbed/Handbook#1078]
If you compare the documentation regarding connectivity configuration, you will notice that between 5.11 and 5.12 the sections were completely lost and mixed up with unrelated stuff.

For comparison, in Mbed OS 5.11 this page: https://os.mbed.com/docs/mbed-os/v5.11/reference/configuration-connectivity.html
contains clear sections and internal table of contents.
You can easily link to relevant sections like this: [Selecting the default interface](https://os.mbed.com/docs/mbed-os/v5.11/reference/configuration-connectivity.html#selecting-the-default-network-interface)

When you compare that to 5.12 documentation: https://os.mbed.com/docs/mbed-os/v5.12/reference/configuration-connectivity.html
All the sections are lost, content is just one big blob that could be produced by running `mbed compile --config -v` and therefore the page does not offer any extra information.

Also, it contains unrelated parameters like `target.boot-stack-size` which should be in platform configuration page.

This page does not anymore document anything. It is just a dump from a script.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1087*

**Comment by AnotherButler** [comment]
The code parameters are pulled straight from the code base. If this page contains incorrect parameters, it means they are incorrect in the code or the script is wrong. Could you please look at the script to see which is the case?

If you or one of your engineers can modify the script to add sections, that could be helpful.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by iriark01** [comment]
@SeppoTakalo unless you or someone else from engineering can modify the script to add sections, I'll close this.
