### ISSUE TITLE
Part of doxygen not generated in the docs engine

### ISSUE THREAD

**Issue by bulislaw** [ARMmbed/Handbook#1089]
The file level doxygen is not reflected in the generated docs:
https://github.com/ARMmbed/mbed-os/blob/master/drivers/MbedCRC.h#L46 is nowhere to be found, I would expect it somewhere linked to CRC either:
https://os.mbed.com/docs/mbed-os/v5.12/apis/mbedcrc.html
https://os.mbed.com/docs/mbed-os/v5.12/mbed-os-api-doxy/classmbed_1_1_mbed_c_r_c.html

I didn't check other files, but I would assume it similar for other APIs. This specific example was pointed out by a customer.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1111*

**Comment by bulislaw** [comment]
Closing as it's an issue with the header file.
