### ISSUE TITLE
Please add UARTSerial to the docs and clarify serial handling

### ISSUE THREAD

**Issue by frmdstryr** [ARMmbed/Handbook#1100]
I spent part of a day trying to get `RawSerial` to work with interrupts only to fail at getting it to work reliably. After digging through various issues I finally found that `UARTSerial` with sigio should be used instead.  UARTSerial works well however it is not mentioned anywhere in any of the "Serial" related doc pages, could this be added?

Also it's a bit confusing what the difference is between `RawSerial`, `Serial`, `USBSerial`, and `UARTSerial`.  Having an explanation of the differences between each of these and when to use them  somewhere would be appreciated (and if it is somewhere it's not easy to find and should be linked in relevant pages) . 

A note on what happens when a new serial object using the `USBTX` and `USBRX` pins is defined in user code (as is done in all the Serial examples) would be helpful as well. Does this override the stdin/stdout serial, conflict with it, etc..?  

## Page link

https://os.mbed.com/docs/mbed-os/v5.13/apis/index.html

## Expected to find...

A reference to UARTSerial as mentioned in https://os.mbed.com/docs/mbed-os/v5.13/apis/filehandle.html

## Found

Nothing in the docs, but did find https://github.com/ARMmbed/mbed-os-5-docs/pull/336 from this repo.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1127*

**Comment by 0xc0170** [comment]
Thanks for reporting, we will review and fix this (I've noticed few other similar reports recently in our issue tracker).

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by MAhmedDev** [comment]
am trying to get UARTserial to work with custom nrf52832 but having no success. I got serial and rawserial to work however they are not buffered. 

Some examples and documentation will be nice :)

**Comment by AnotherButler** [comment]
@Masitech Thanks for commenting 👍 We now have documentation for BufferedSerial in our v6.0-preview branch: https://os.mbed.com/docs/mbed-os/v6.0-preview/apis/bufferedserial.html

Please note this branch is a preview and a work in progress.

**Comment by AnotherButler** [comment]
We believe we answered this question, so I'm closing this issue. Please feel free to reopen it if it has not been resolved.
