### ISSUE TITLE
SDBlockDevice example doesn't import

### ISSUE THREAD

**Issue by pabloassembler** [ARMmbed/Handbook#1101]
SDBlockDevice example on

https://os.mbed.com/docs/mbed-os/v5.13/apis/sdblockdevice.html

doesn't import as a program. Instead, a full directory os examples is imported.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1129*

**Comment by AnotherButler** [comment]
@pabloassembler Thank you for raising this issue. We're looking into it.

**Comment by AnotherButler** [comment]
Thank you for bringing this to our attention. For this example, we have disabled the button causing the unexpected behavior and ask that you [copy the example into a new program](https://os.mbed.com/docs/mbed-os/v5.13/tools/creating-a-new-program.html) rather than importing it directly.

**Comment by AnotherButler** [comment]
Please feel free to reopen this issue if you feel it has not been resolved.
