### ISSUE TITLE
Broken link in porting HAL module page

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/Handbook#1102]
# Docs issue template

## Page link
https://os.mbed.com/docs/mbed-os/v5.13/porting/porting-hal-modules.html

Text / link: "You can see an example using the CC3220SF-LAUNCHXL board." --> https://github.com/ARMmbed/mbed-os-examples-docs_only/blob/master/Baremetal-Blinky/main.cpp

## Expected to find...

Example mentioned in docs.

## Found

"Page not found"

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1132*

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1133*

**Comment by AnotherButler** [comment]
That example has been updated, and it has changed names. It's linked immediately after the broken link, so I'm removing the duplicated broken link. I'll mark this as resolved once the change has merged to all affected versions.
