### ISSUE TITLE
DTLSSocket example is wrong

### ISSUE THREAD

**Issue by dreamlich** [ARMmbed/Handbook#1105]
# Docs issue template
DTLSSocket example is wrong. It is an example for TLSSocket but not DTLSSocket.
## Page link
https://os.mbed.com/docs/mbed-os/v5.13/apis/dtlssocket.html

## Found

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1136*

**Comment by AnotherButler** [comment]
@dreamlich Thanks for contacting us.
DTLSSocketWrapper inherits TLSSocketWrapper and uses the same API. That's why this API uses the same example as TLSSocket.

**Comment by AnotherButler** [comment]
Please feel free to reopen this ticket if you feel this issue has not been resolved.
