### ISSUE TITLE
How to define a macro definition on mbed compiler?

### ISSUE THREAD

**Issue by rise0chen** [ARMmbed/Handbook#1114]
How to define a macro definition on mbed compiler?like `gcc -D xxx xxx`

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1142*

**Comment by rise0chen** [comment]
Can't resolve DNS.

**Comment by AnotherButler** [comment]
Hi, @rise0chen . You can define macros through the configuration system. You can find documentation about it in the [configuration section](https://os.mbed.com/docs/mbed-os/v5.13/reference/configuration.html) and the following pages. Please let us know if you have further questions.

**Comment by rise0chen** [comment]
I see,thx.
![image](https://user-images.githubusercontent.com/12853908/61258452-57268f80-a7a8-11e9-8378-2ac3bbc90054.png)
