### ISSUE TITLE
Add sudo to install mbed-cli

### ISSUE THREAD

**Issue by doom-fr** [ARMmbed/Handbook#1129]
# Docs issue template
command `pip install mbed-cli` does not work on `Ubuntu 18.04.LTS`

## Page link
https://os.mbed.com/docs/mbed-os/v5.11/tools/linux.html

## Expected to find...
`sudo pip install mbed-cli`
or maybe `sudo -H pip install mbed-cli`

## Found
`pip install mbed-cli`

which produce ...
```
doom@doom-PC:~$ pip install mbed-cli
Collecting mbed-cli
  Downloading https://files.pythonhosted.org/packages/f8/2d/a40a9ef436094dd6fcdf05fd010446baa5c336d36f97ff50415208f31f18/mbed-cli-1.10.0.tar.gz (52kB)
    100% |████████████████████████████████| 61kB 1.7MB/s 
Building wheels for collected packages: mbed-cli
  Running setup.py bdist_wheel for mbed-cli ... done
  Stored in directory: /home/doom/.cache/pip/wheels/1e/69/7c/80a72c06d1f064cbacb8729df2315629e71dfafa1d922c3222
Successfully built mbed-cli
Installing collected packages: mbed-cli
Successfully installed mbed-cli-1.10.0
doom@doom-PC:~$ mbed config --list

Command 'mbed' not found, did you mean:

  command 'mred' from deb racket
  command 'med' from deb ncl-ncarg
  command 'msed' from deb mblaze

Try: sudo apt install <deb name>

doom@doom-PC:~$ mbed help

Command 'mbed' not found, did you mean:

  command 'msed' from deb mblaze
  command 'med' from deb ncl-ncarg
  command 'mred' from deb racket

Try: sudo apt install <deb name>
```

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1165*

**Comment by doom-fr** [comment]
my DNS do not know jira.arm.com

https://dnschecker.org/#A/jira.arm.com

**Comment by AnotherButler** [comment]
@madchutney @mark-edgeworth Could one of y'all please help with this?

@doom-fr As a side note, are you using Mbed OS 5.11? If you're using the latest version (Mbed OS 5.13), you can find the most recent documentation here: https://os.mbed.com/docs/mbed-os/latest/tools/manual-installation.html.

**Comment by doom-fr** [comment]
I have used the default `mbed-os-example-blinky`

In the new version of doc, it is still `pip install mbed-cli`, no `sudo` !

**Comment by RomanSaveljev** [comment]
https://askubuntu.com/a/802594 explains why `sudo pip install` is a bad practice. I think it should not be encouraged by the official documentation. If one uses virtual environment, then plain `pip install mbed-cli` will succeed. If one does not, then calling `pip install --user` is the way to avoid `sudo`.

**Comment by doom-fr** [comment]
OK but `pip install --user mbed-cli` does not work too.
(Maybe it does not work on my machine because it is not a fresh install)
Anyway, it is not written in the documentation.

And for `sudo`, Pip uses SSL. No ? So there can't be man in the middle.
Not sure of that.

But in the documentation, what's sure is that it should be written a command line that works.
And for now, it is not the case.

**Comment by AnotherButler** [comment]
ping @madchutney @mark-edgeworth

**Comment by mark-edgeworth** [comment]
> my DNS do not know jira.arm.com
> 
> https://dnschecker.org/#A/jira.arm.com

This is a reference to ARM's internal bug tracking system only and is not externally visible.

**Comment by mark-edgeworth** [comment]
The installation of mbed-cli is not as painless as we'd like, and we're not even sure that it works on Ubuntu at the moment. We are looking at how this can be improved.  Having said that, may I suggest that you install this into a virtual python environment (eg pipenv) which may resolve some of the issues you are having.

**Comment by mark-edgeworth** [comment]
Just to be clear, using sudo to force the installation is not recommended at all. It could appear to fix the problem, but it could also introduce other unexpected changes in your python environment.

**Comment by AnotherButler** [comment]
Thanks for raising this issue. We believe we have solved it by adding instructions to use a virtual environment: https://github.com/ARMmbed/mbed-os-5-docs/pull/1143.

Please feel free to reopen if this issue has not been resolved.
