### ISSUE TITLE
compiling-the-code.html has no windows info

### ISSUE THREAD

**Issue by mj8w** [ARMmbed/Handbook#1135]
# Docs issue template

## Page link
https://os.mbed.com/docs/mbed-os/v5.13/quick-start/compiling-the-code.html
## Expected to find...
CLI instructions for windows
## Found
Apparently Linux CLI?

**Comment by mj8w** [comment]
Oh. It is right, except the prompt is not the same. Also, you have to open a new cmd shell, after the install is complete.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1202*

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1203*

**Comment by AnotherButler** [comment]
@mj8w How would you recommend we clarify this to minimize future confusion?

**Comment by mj8w** [comment]
What happened in my case (which I should have known better), is I already had a cmd prompt window open, while it installed, and forgot that the PATH would be re set. When I tried mbed, nothing worked.
The thing is, you can't tell what the prompt (on the webpage) means, like is this the cmd prompt, or something else? Maybe I was supposed to open an mbed app and then I get this prompt?
I think the page needs to explicitly state: "When the installation is complete, open a cmd or bash shell, and enter the following..." That would have made it clear to me.

**Comment by AnotherButler** [comment]
We have merged PR #1138 to resolve this issue. Please feel free to reopen it if this does not solve it.
