### ISSUE TITLE
Error on NetworkInterface set_blocking() docs. 

### ISSUE THREAD

**Issue by javiermelendezc** [ARMmbed/Handbook#1136]
https://os.mbed.com/docs/mbed-os/v5.13/mbed-os-api-doxy/class_network_interface.html#aaf6bf1dfffbe6a5626b7b52eaa542b6e

Documentation on connect() and disconnect() says:

> This blocks until connection is established, but asynchronous operation can be enabled by calling NetworkInterface::set_blocking(false).

Then in set_blocking() parameters description it says:

> virtual nsapi_error_t set_blocking(bool blocking)
> ....
> blocking | Use true to set NetworkInterface in asynchronous mode.

I think it should be: **Use false to set NetworkInterface in asynchronous mode.**

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1206*

**Comment by AnotherButler** [comment]
@SeppoTakalo Could someone on your team please review this? I think it must be fixed in the code.

**Comment by AnotherButler** [comment]
ping @jarlamsa @SeppoTakalo

**Comment by jarlamsa** [comment]
@AnttiKauppila has the responsibility of connectivity. And yes, it seems to be a mistake in the set_blocking doxygen.

**Comment by AnttiKauppila** [comment]
https://github.com/ARMmbed/mbed-os/pull/11341

**Comment by AnotherButler** [comment]
@javiermelendezc Thanks for raising this. We believe it's resolved by this PR: https://github.com/ARMmbed/mbed-os/pull/11341

Please feel free to reopen this if it is not resolved.
