### ISSUE TITLE
Specify full directory path on "Working with mbed CLI" user guide 

### ISSUE THREAD

**Issue by TheNageek** [ARMmbed/Handbook#1139]
# Full path to MBED_OS_DIR not specific in guide
Minor clarification, but when attempting to follow the guide, at the link below, specifically for managing multiple projects, could clarify that the path to the projects directory should be the full path, not just the immediate path when setting MBED_OS_DIR global, example below

`/home/user/workspace/mbed-os`

NOT

`workspace/mbed-os`

https://os.mbed.com/docs/mbed-os/v5.13/tools/working-with-mbed-cli.html

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1208*

**Comment by AnotherButler** [comment]
@CuriousEngineering Thanks for raising this issue 👍 

If you're interested in contributing a fix to this or any other documentation issue, our documentation contributions follow the [same guidelines as our code](https://os.mbed.com/docs/mbed-os/v5.13/contributing/index.html) (as applicable).

**Comment by AnotherButler** [comment]
We have merged PR #1141 to resolve this issue.
