### ISSUE TITLE
Mbed OS Docs are out of date, confusing and misleading.

### ISSUE THREAD

**Issue by star297** [ARMmbed/Handbook#1169]
# Docs issue template
Mbed-os v5.14 docs and examples appear to be from earlier versions.
It's less confusing to have a blank page indicating an 'under construction' or 'Documentation not ready' label on these pages.
The example indicates the use of 'wait' however the api information states depreciated since v5.14    

## Page link
https://os.mbed.com/docs/mbed-os/v5.14/apis/wait.html
https://os.mbed.com/docs/mbed-os/v5.14/mbed-os-api-doxy/mbed__wait__api_8h_source.html

## Expected to find...
Correct information

## Found
Out of date and depreciated information

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1311*

**Comment by AnotherButler** [comment]
Thank you for raising this issue. We're looking into it now.

**Comment by AnotherButler** [comment]
We've created PRs #1170 and #1180 to address this issue. Please feel free to reopen it or open a new one if you have further questions.

**Comment by hadefuwa** [comment]
I'm so put off by Mbed due to the sheer amount of outdated and deprecated articles.

**Comment by 0xc0170** [comment]
> I'm so put off by Mbed due to the sheer amount of outdated and deprecated articles.

Can you provide examples , what articles shall we clean up? You can create a new issue with more details that could help us to fix them.
