### ISSUE TITLE
Mbed OS build rules

### ISSUE THREAD

**Issue by tdjastrzebski** [ARMmbed/Handbook#1179]
In [Mbed OS build rules](https://os.mbed.com/docs/mbed-os/v5.10/tools/mbed-os-build-rules.html) I found nothing about **include** folders.
**mbed-os** contains 10+ **include** folders. It seems those folders contain headers which are not referenced (neither directly nor indirectly) but which have to be included.
This is undocumented.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1332*

**Comment by AnotherButler** [comment]
@madchutney @mark-edgeworth Could one of you please point me to or provide me with content about include folders, so I can add it to the documentation?

**Comment by 0xc0170** [comment]
The link referenced above contain sources, but might be worth documenting what header extensions are supported.

Everything that is not skipped is included - every header file found in these folders is being added (following rules about TARGET, FEATURE, COMPONENT, TOOLCHAIN). A simple note might added to the build rules?

**Comment by tdjastrzebski** [comment]
@0xc0170 @AnotherButler @madchutney @mark-edgeworth
I am not certain it is worth starting a new thread but here is another build issue I came across.
`mbed-os\features\cryptocell\FEATURE_CRYPTOCELL310\include\ccsw_crys_rsa_shared_types.h` header file uses `uint32_t` type while this header has no `#include` directives at all - I guess `stdint.h` would be needed.
The problem arose while compiling `mbed-os\features\cryptocell\FEATURE_CRYPTOCELL310\trng.c`.

This makes me believe thare are some additional, undocumented build rules which must be followed. Probably `stdint.h` should be forcefully included but I am not certain. Maybe this is just a bug - missing `#include <stdint.h>`.

**Comment by mark-edgeworth** [comment]
Regarding this last point. I don't think the build system is doing anything strange here. Whenever ccsw_crys_rsa_shared_types.h is included in a source unit, there will be a preceding #include of something like stdint.h that defines uint32_t. The header is not compiled on its own.

**Comment by tdjastrzebski** [comment]
@mark-edgeworth I suspect that the order in which header files are forcefully included matters. Otherwise `ccsw_crys_rsa_shared_types.h` would not compile. If this is the case, I suggest following [headers best practices](https://www.acodersjourney.com/top-10-c-header-file-mistakes-and-how-to-fix-them/) - see **MISTAKE # 4: Not making the header file compliable by itself**.
New issue #1196 created

**Comment by tdjastrzebski** [comment]
@AnotherButler Probably there are some other undocumented build rules. E.g. `objects_cryptocell.h` header is not included anywhere, does not lay in `includes` folder but definitely is needed by `trng.c`.

**Comment by mark-edgeworth** [comment]
> @mark-edgeworth I suspect that the order in which header files are forcefully included matters. Otherwise `ccsw_crys_rsa_shared_types.h` would not compile. If this is the case, I suggest following [headers best practices](https://www.acodersjourney.com/top-10-c-header-file-mistakes-and-how-to-fix-them/) - see **MISTAKE # 4: Not making the header file compliable by itself**.
> New issue #1196 created

Completely agree, although this is outside of the build tools remit I'm afraid.

**Comment by tdjastrzebski** [comment]
I reported another potential code issue: ARMmbed/mbed-os#12252

**Comment by AnotherButler** [comment]
I've put up this PR to address the initial concern: https://github.com/ARMmbed/mbed-os-5-docs/pull/1260

**Comment by mark-edgeworth** [comment]
As hinted at earlier, the correct fix for this is to correct the header file(s) in question so that they include whatever other headers that they require to provide all of the type definitions etc needed.

**Comment by AnotherButler** [comment]
Thanks for clarifying. I thought when @0xc0170 said "A simple note might added to the build rules?", that was the requested fix. 

Because the only fix is changes to the header files, and it looks like https://github.com/ARMmbed/mbed-os/issues/12244 addresses this, shall I close this issue?

**Comment by mark-edgeworth** [comment]
Yes, I reckon so. Thanks A!

**Comment by tdjastrzebski** [comment]
@AnotherButler by tracing what exactly `mbed` Python build script is doing I figured out that actually all paths have to be included.
