### ISSUE TITLE
Thread docs need to deprecate Wait ? 

### ISSUE THREAD

**Issue by LMESTM** [ARMmbed/Handbook#1186]
# Docs issue template

Hasn't wait API been deprecated and replaced by sleep_for in latest versions ? 

## Page link
https://os.mbed.com/docs/mbed-os/v5.9/reference/thread.html

## Expected to find...
update on deprecated and recommended APIs

**Comment by AnotherButler** [comment]
@LMESTM Thanks for raising this issue. That page links to the 5.9 documentation. We have added updates in the latest documentation, which will go out in 5.15.

**Comment by LMESTM** [comment]
@AnotherButler 
Do you mean there should be another up-to-date page like : 
https://os.mbed.com/docs/mbed-os/v5.15/reference/thread.html
I haven't found any more recent version than the V5.9  ...

**Comment by kjbracey** [comment]
Latest version is here: https://os.mbed.com/docs/mbed-os/v5.14/apis/thread.html

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1339*

**Comment by AnotherButler** [comment]
Please feel free to reopen this issue if the link provided in the most recent comment doesn't resolve this issue.
