### ISSUE TITLE
Make header files compliable by themselves

### ISSUE THREAD

**Issue by tdjastrzebski** [ARMmbed/Handbook#1196]
I suspect that the order in which header files are forcefully included during build matters. Otherwise `ccsw_crys_rsa_shared_types.h` would not compile since it uses `uint32_t` type without including `<sdtint.h>`.
If this is the case, I suggest following [headers best practices](https://www.acodersjourney.com/top-10-c-header-file-mistakes-and-how-to-fix-them/) - **MISTAKE # 4: Not making the header file compliable by itself**.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1365*

**Comment by AnotherButler** [comment]
@tdjastrzebski  This looks like a code issue, not a documentation issue. Could you please raise this issue against the [`mbed-os` repository](https://github.com/ARMmbed/mbed-os/issues)?

**Comment by mark-edgeworth** [comment]
Yes, this is a code issue.

**Comment by tdjastrzebski** [comment]
Issue ARMmbed/mbed-os#12244 has been reported

**Comment by AnotherButler** [comment]
@tdjastrzebski Thank you. I'll close this issue here, so we can follow it in the new `mbed-os` issue you've raised.
