### ISSUE TITLE
This pages links to the deprecated ARM embedded toolchain page on launchpad

### ISSUE THREAD

**Issue by mjs-arm** [ARMmbed/Handbook#121]
The home of ARM embedded toolchain has moved to:

https://developer.arm.com/open-source/gnu-toolchain/gnu-rm

**Comment by iriark01** [comment]
@AnotherButler on dev_tools/third_party.md (line 82) - can you verify and fix for all versions, please?

**Comment by AnotherButler** [comment]
@mjs-arm @iriark01 I have fixed this for all versions. Is this OK to close?
