### ISSUE TITLE
PSA Attestation API page doesn't specify the spec version

### ISSUE THREAD

**Issue by adrianlshaw** [ARMmbed/Handbook#1217]
## Page link

https://os.mbed.com/docs/mbed-os/v5.15/apis/psa-initial-attestation.html

## Expected to find...

The version of this PSA API implemented is missing. The API version on this page is `1.0 beta0`.

This is important for end users to note because there was a breaking change between`1.0 beta0` and `1.0 stable`. TF-M is also in the processing of merging `1.0 stable` into upstream, so it would be best to avoid confusion (especially since this is the second result on Google search). 

Also there ought to be a reference to the spec document identifier (ARM IHI 0085).

## Found

Nothing.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1417*

**Comment by AnotherButler** [comment]
@adrianlshaw Could you please elaborate more? Which link is out of date? The link to the TF-M repository? Or is the Doxygen, itself, out of date?

**Comment by adrianlshaw** [comment]
No links are out of date. I am just saying that the text at the top of the page should specify the version of the API.

So replace:

"The initial attestation service exposes the following PSA interfaces"
 
with

"The initial attestation service exposes the following interfaces (based on the Beta-0 spec of the PSA Attestation API)"

**Comment by AnotherButler** [comment]
Thanks for clarifying 👍 

When will we need to do something with `1.0 stable`?

**Comment by adrianlshaw** [comment]
> When will we need to do something with 1.0 stable?

As soon as Mbed implements it :-) but I don't know when that might happen (I'm not in ISG).

**Comment by AnotherButler** [comment]
PR #1221 has merged, so I'm closing this issue. Please reopen it if it needs further resolution.
