### ISSUE TITLE
Target repository referenced does not exist

### ISSUE THREAD

**Issue by keepitsimplejim** [ARMmbed/Handbook#1233]
Repository referenced to for the baseline target template sends you to a repository that does not exits.
Edit: on second reading this could be a reference to how to name a development git branch, so this could do with clarification.
## Page link
https://os.mbed.com/docs/mbed-os/v5.15/porting/porting.html
## Expected to find...
Template for a new target at https://github.com/ARMmbed/mbed-os-new-target 
## Found
404 page not found.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1440*

**Comment by AnotherButler** [comment]
@keepitsimplejim Thank you for raising this issue. Yes, this shows how to name the branch, but I see how that's not clear. I'll put up a PR clarifying this.

**Comment by AnotherButler** [comment]
I've put up PR 1261 to resolve this issue. Please take a look, and let us know if this makes more sense.

**Comment by AnotherButler** [comment]
We believe we have fixed this issue. Please feel free to reopen this ticket or start a new one if further changes are needed.
