### ISSUE TITLE
Missing Visual Studio Code Exporter from CLI

### ISSUE THREAD

**Issue by pfried** [ARMmbed/Handbook#126]
There is an article in the Handbook describing the use of a VSC debugger. 

https://docs.mbed.com/docs/mbed-os-handbook/en/latest/debugging/vscode/

The CLI command

`$ mbed export -i vscode_gcc_arm -m K64F`

should export a program to VSC but there is no such exporter

**Comment by iriark01** [comment]
@janjongboom can you help?

**Comment by janjongboom** [comment]
@pfried @iriark01 We're waiting on some work by Microsoft... See https://github.com/ARMmbed/mbed-os/pull/3915.

To get it to work right now:

```
cd mbed-os
git remote add janjongboom git@github.com:janjongboom/mbed-os.git
git fetch janjongboom
git checkout janjongboom/feature-vscode
cd ..
mbed export -i vscode_gcc_arm -m K64F
```

After that you can switch back to whatever mbed OS version you were on before.

**Comment by AnotherButler** [comment]
@janjongboom @pfried Is this OK to close because ARMmbed/mbed-os#3915 has been merged, or is this still an open issue?

**Comment by janjongboom** [comment]
@AnotherButler Yes, can be closed.

BUT... The vscode page is removed from handbook, so it should be reinstantiated.
