### ISSUE TITLE
Build and host

### ISSUE THREAD

**Issue by geoffrey-vl** [ARMmbed/Handbook#1264]
Hi,
I've noticed that the docs for our version of mbed-os went deprecated.
I'm wondering how we can build the docs (this repo) ourselves, and host it on our on-premise server.

Any guidelines?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1466*

**Comment by iriark01** [comment]
I'll look into a couple of options and get back to you ASAP. Could you tell me which version you need?

**Comment by geoffrey-vl** [comment]
5.9.2

**Comment by iriark01** [comment]
I can send you a ZIP of the version that you can deploy locally. Will that help?

**Comment by geoffrey-vl** [comment]
For me, yes

**Comment by AnotherButler** [comment]
We believe we have resolved this issue, so I'm closing it. Please let us know if we can be of further help.

**Comment by geoffrey-vl** [comment]
Yes its ok, thanks
