### ISSUE TITLE
PyOCD deploy failed, deploying using mass storage device...

### ISSUE THREAD

**Issue by Hammie217** [ARMmbed/Handbook#1267]
# Description
After compilation of my c++ code after trying to upload to the device I get the error `PyOCD deploy failed, deploying using mass storage device...`.
It started happening out of nowhere and I've tried different boards and deleting sections of code to no avail.  

The code can be found here:
https://github.com/Hammie217/NXPCupGroupProject/blob/master/main.cpp

**Comment by AnotherButler** [comment]
@Hammie217 Thank you for raising this issue. This appears to be a code issue and not a documentation issue. Could you please raise this issue in the [`mbed-os` repository](https://github.com/ARMmbed/mbed-os), instead? That's where the code lives and where we keep all of our code issues. This repository is just for documentation.

**Comment by Hammie217** [comment]
Apologies!, I clicked the wrong repo!
