### ISSUE TITLE
Unit test section external link to documentation returns 404

### ISSUE THREAD

**Issue by keepitsimplejim** [ARMmbed/Handbook#1309]
## Page link
https://os.mbed.com/docs/mbed-os/v5.15/tools/unit-testing.html#unit-testing-with-mbed-cli

## Expected to find...
In the text "See the documentation for Google Mock if you want to write and use C++ mock classes instead of stubs." the link to "documentation Google Mock" should link to the relevant documentation.

## Found
Link sends you to the 404 page on GiHhub.

**Comment by iriark01** [comment]
Thank you very much; I've replaced the link in the relevant versions and am closing the issue as resolved.
