### ISSUE TITLE
Baremetal porting guide asks to edit non-existent files

### ISSUE THREAD

**Issue by Patater** [ARMmbed/Handbook#1323]
Baremetal porting guide instructions don't work because they are missing a step to `mbed deploy` before editing files within the `mbed-os` folder. We can use `mbed import` to clone and deploy in one go, instead of lengthier instructions about using `git`.

Found during OOB testing of `mbed-os-6.0.0-rc1`.

# Docs issue template

## Page link

https://os.mbed.com/docs/mbed-os/development/bare-metal/porting-a-target-from-mbed-os-2-to-mbed-os-6-bare-metal.html

## Expected to find...

N/A

## Found

N/A

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1546*
