### ISSUE TITLE
Permissive Binary License sometimes referred to as Public Binary License

### ISSUE THREAD

**Issue by adamgreen** [ARMmbed/Handbook#133]
In the https://github.com/ARMmbed/Handbook/blob/5.4/docs/cont/contributing.md#how-to-apply-pbl-correctly section of the Handbook the PBL is sometimes expanded to **Public Binary License** but in most places (including the legal license description), it is referred to as the **Permissive Binary License**.

Examples of where it appears to be named incorrectly in this section:
<pre>Unless specifically indicated otherwise in a file, files are licensed under the Public Binary License, 
as can be found in: LICENSE-permissive-binary-license-1.0.txt</pre>

* The full original [Public Binary License 1.0 text](https://www.mbed.com/licenses/PBL-1.0) in *LICENSE-permissive-binary-license-1.0.txt*.

**Comment by AnotherButler** [comment]
@jlovejoy Could you please help me fix the wording?

**Comment by jlovejoy** [comment]
Good catch! yes, it should be "permissive" not "public" (or unofficially, PB might refer to someone's initials... ;)
I just submitted a PR, as the header notice needed a bit updating that @pjbakker and I came up with some time ago, but forgot to update it here as well.

**Comment by AnotherButler** [comment]
Thank you so much. You are awesome.

**Comment by AnotherButler** [comment]
Thanks for raising this issue, @adamgreen. We just merged PR #137, which should resolve this issue.

**Comment by adamgreen** [comment]
Thanks @AnotherButler and @jlovejoy.
