### ISSUE TITLE
Remove/update references to the Windows serial driver

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/Handbook#1332]
# Docs issue template

The Serial driver is no longer needed on Windows 10.
In fact, it creates a problem when trying to use WebUSB.
See https://github.com/ARMmbed/DAPLink/issues/487
I also hit this problem myself and it took me a while to find out.

## Page link

https://os.mbed.com/docs/mbed-os/v5.15/tutorials/windows-serial-driver.html
And possibly many more that refer to windows serial driver.

## Expected to find...

Details that the driver is needed for old versions of Windows (7 and older) and it's not required for Windows 10.
Discourage the installation of the serial driver.

## Found

Recommendations to install the driver on Windows

---

FYI @iriark01 @thegecko @arekzaluski

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1553*

**Comment by thegecko** [comment]
It's also mentioned on the DAPLink page of mbed.com (albeit outlining not Windows 10 in the text):

https://os.mbed.com/handbook/DAPLink

As Windows 7 is EOL and no longer supported and this shouldn't be used on newer Windows, what would be the impact of removing it altogether?

At the very least, we need a large warning banner in both places for users to not use it on Windows 8.1 or 10.

@JoeTheGuitarist thoughts?

**Comment by JoeTheGuitarist** [comment]
It should ideally be removed altogether, but starting with a clear warning message anywhere the drivers are mentioned would suffice for now. FYI - Windows 7 represents only about 10% of all Windows usage of our website and has declined significantly in the last 6 months.

**Comment by LDong-Arm** [comment]
@MarceloSalazar Thanks for raising this issue.

@thegecko @JoeTheGuitarist @arekzaluski 
I guess we can remove it from the documentation altogether. The [Mbed CLI Windows installer](https://github.com/ARMmbed/mbed-cli-windows-installer/releases) already includes the serial driver and gets installed (or not) depending on the Windows version. The user shouldn't need to do anything about it at all.

I'll update the documentation.

**Comment by iriark01** [comment]
What if they're not using Mbed CLI? Will they have a problem if they're using the Online Compiler?

**Comment by MarceloSalazar** [comment]
Note the Mbed CLI installer hasn't been updated for a while and may never do. 
Instead of relying on the installer, I'd suggest we inform that the driver is only required for Windows 7 and older versions. This doc could be removed in the future.

**Comment by LDong-Arm** [comment]
Okay, fair point

**Comment by LDong-Arm** [comment]
I've created #1334.

As for https://os.mbed.com/handbook/DAPLink, it's an old Mbed OS 2 page which may not be updated anymore?
