### ISSUE TITLE
Invalid reference to pelion E2E tests

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/Handbook#1345]
## Page link

https://www.pelion.com/docs/device-management/current/porting/test-pal.html

## Expected to find...

An explanation of E2E tests or a link to a valid page.

## Found
"Detailed information on the E2E tests and their execution is available in the E2E tests README document."

README document link is bad. It goes to this, which is invalid. 
https://github.com/ARMmbed/mbed-cloud-client-example/blob/master/TESTS/E2E/README.md

## Other details
There is useful information in these documents. Perhaps the first one is the right one.
https://github.com/ARMmbed/mbed-cloud-client-example/blob/master/TESTS/README.md
https://github.com/ARMmbed/pelion-e2e-python-test-library/blob/master/README.md

However, I think that it would be good to include some of the key information in the documentation and not just rely on readme files.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1583*

**Comment by iriark01** [comment]
@AnotherButler this is for Pelion docs, not Mbed OS. Please review and close this issue when you've moved it across.

**Comment by AnotherButler** [comment]
As a first step, I have fixed the link on versions 2.2 through 4.5, so it no longer 404s.

**Comment by iriark01** [comment]
Thanks, Amanda. 

I am going to close this, as it's on the wrong GitHub repository.

**Comment by maclobdell** [comment]
oops, my bad. wrong repo. thanks
