### ISSUE TITLE
How to add a QSPI memory on custom boards

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/Handbook#1347]
# Docs issue template

## Page link

https://os.mbed.com/docs/mbed-os/v6.0/apis/spi-apis.html

## Expected to find...

See https://github.com/ARMmbed/mbed-os/issues/13189

Doc need more information for customers adding an QSPI

@MarceloSalazar @0xc0170

## Found

Nothing

**Comment by MarceloSalazar** [comment]
@jeromecoutant thanks for raising this
I think we may need to expand the content on Blockdevice porting in general, not only for custom boards
https://os.mbed.com/docs/mbed-os/v6.0/porting/blockdevice-port.html
Would you agree?

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1590*
