### ISSUE TITLE
Bad link to tutorial about optimizing binary size

### ISSUE THREAD

**Issue by 0Grit** [ARMmbed/Handbook#1355]
# Docs issue template

## Page link

https://os.mbed.com/docs/mbed-os/v6.2/quick-start/further-reading.html

## Expected to find...

A tutorial on optimizing binary size.

## Found

![image](https://user-images.githubusercontent.com/24318071/89474132-bdcf7000-d752-11ea-92de-3532d0adb0d0.png)

The link went to: https://os.mbed.com/docs/mbed-os/v6.2/apis/platform-tutorials.html instead

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1642*

**Comment by iriark01** [comment]
Thank you for your feedback. We do not have a tutorial explicitly dealing with binary size; the link text is wrong, and I will correct it to say "Optimizing memory and power".

**Comment by iriark01** [comment]
Link text fixed: https://os.mbed.com/docs/mbed-os/v6.2/quick-start/further-reading.html
