### ISSUE TITLE
os.mbed.com > Mbed 6.2 > Docs › Build tools › Mbed CLI › Create: program root version control discussion unclear

### ISSUE THREAD

**Issue by morrisrx** [ARMmbed/Handbook#1360]
# Docs issue

Mbed 6.2 > Docs › Build tools › Mbed CLI › Create> Understanding the working context and program root > says:

“Various Mbed CLI features require a program root, which should be under version control - either Mercurial.”

The “- either Mercurial” seems to indicate there is another version control system in addition to Mercurial (perhaps Git?). If there is another VCS it should say something like: “- Mercurial or Git”. If there is no other VCS it should say something like: “- Mercurial”.

## Page link

https://os.mbed.com/docs/mbed-os/v6.2/build-tools/create.html

## Expected to find...

“Various Mbed CLI features require a program root, which should be under version control - Mercurial.”

Or

“Various Mbed CLI features require a program root, which should be under version control - either Mercurial or Git.”

## Found

“Various Mbed CLI features require a program root, which should be under version control - either Mercurial.”

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-1656*

**Comment by iriark01** [comment]
Fixed in all live versions; will rebuild today. Thank you very much for your feedback.
