### ISSUE TITLE
Broken link to bootloader example

### ISSUE THREAD

**Issue by rdvmikko** [ARMmbed/Handbook#1372]
# Docs issue template

## Page link
https://os.mbed.com/docs/mbed-os/v6.4/program-setup/creating-and-using-a-bootloader.html

## Expected to find...
A working link to the example

## Found
A broken link.

To find the link please search for text "Please see the bootloader example for an example on how to use the bootloader feature". The link points to https://github.com/ARMmbed/mbed-os-example-feature-bootloader which apparently does not exist.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2595*

**Comment by iriark01** [comment]
Thank you for reporting this issue. It has now been fixed in all live versions.
