### ISSUE TITLE
Confused description in the chapter of porting

### ISSUE THREAD

**Issue by tz-arm** [ARMmbed/Handbook#138]
There are some reference commend in the porting chapter as below.
Actually there is no "mbed-os-example-new-target" repository and mbed import will be fail.
Is it a typo which want to use "mbed new" or there was such a repository?

ps:
- mbed import mbed-os-example-new-target
- cd mbed-os-example-new-target\mbed-os
- git checkout master
- git pull
- git checkout -b my-new-target
- git remote set-url origin https://github.com/USERNAME/mbed-os
- cd ..

**Comment by AnotherButler** [comment]
@tz-arm I think PR #143 has resolved this issue. Is it OK to close, or is anything still unresolved?

**Comment by AnotherButler** [comment]
@tz-arm I am closing this issue. Please don't hesitate to reopen it if anything is still unresolved.
