### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by betzw** [ARMmbed/Handbook#14]
Document `docs/advanced/config_system.md` contains broken links to something which seems to be a porting guide in particular to this [page](https://github.com/ARMmbed/Porting_Guide/blob/master/docs/porting/Targets.md). Where can I find this "Porting Guide"?

**Comment by iriark01** [comment]
Afraid the porting guide hasn't been published yet. I've replaced the link with a "coming soon" message. Thank you for pointing it out!

**Comment by betzw** [comment]
Any idea when this very interesting porting guide will be published?
How can I get notified once its gonna be published?
