### ISSUE TITLE
Please update stale hyperlink for Googletest primer

### ISSUE THREAD

**Issue by ghost** [ARMmbed/Handbook#1400]
The Googletest primer has been moved to the top-level [docs](https://github.com/google/googletest/blob/master/docs) directory, so the hyperlink on this page is stale. 

## Page link
https://os.mbed.com/docs/mbed-os/v6.6/debug-test/unit-testing.html

## Expected to find...
[documentation for Google Test](https://github.com/google/googletest/blob/master/docs/primer.md)

## Found
[documentation for Google Test](https://github.com/google/googletest/blob/master/googletest/docs/primer.md)

**Comment by ciarmcom** [comment]
@noonfom This issue has an incomplete or old issue template.For future reference please use an up to date clone of the repository before raising issues. Many thanks.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3314*

**Comment by 0xc0170** [comment]
@noonfom Can you send a pull request fixing this url?

**Comment by ghost** [comment]
@0xc0170 Sure. I opened #1402 to resolve this issue.

**Comment by ChrisGooch-Arm** [comment]
The above fix was accepted and merged and published as of v6.8:

https://os.mbed.com/docs/mbed-os/v6.8/debug-test/unit-testing.html
