### ISSUE TITLE
Going from mbed CLI1 to mbed CLI2 - no documentation provided

### ISSUE THREAD

**Issue by ralphrmartin** [ARMmbed/Handbook#1436]
# Docs issue template

## Page link
https://os.mbed.com/docs/mbed-os/v6.9/build-tools/mbed-cli-2.html

## Expected to find...
Some instructions for how to convert an mbed CLI1 project into an mbed CLI2 project.

## Found
No information on the topic at all

**Comment by ciarmcom** [comment]
@ralphrmartin This issue has an incomplete or old issue template.For future reference please use an up to date clone of the repository before raising issues. Many thanks.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3705*

**Comment by LDong-Arm** [comment]
We added a migration guide in #1441 so the latest docs contain it. I'm closing this issue, but please feel free to open a new one if anything is missing.
