### ISSUE TITLE
Define RTX

### ISSUE THREAD

**Issue by BurtHarris** [ARMmbed/Handbook#1445]
# Docs issue template

## Page link
https://os.mbed.com/docs/mbed-os/v6.9/introduction/index.html contains an introduction to using the terms RTOS and RTX without introduction or definition.   The glossary at https://os.mbed.com/docs/mbed-os/v6.9/introduction/glossary.html contains an entry for RTOS, but ...

## Expected to find...
RTX seems undefined.    

## Found
Seems like platform-specific jargon, and is hard to understand for developers familiar with another platform.

**Comment by ciarmcom** [comment]
@BurtHarris This issue has an incomplete or old issue template.For future reference please use an up to date clone of the repository before raising issues. Many thanks.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3829*

**Comment by BurtHarris** [comment]
@ciarmcom To clarify your reference to an _up to date clone of the repository_, please recognize I've not cloned this repository at all.    

I was reading docs online from https://os.mbed.com/docs, followed the [Report an issue on github](https://github.com/ARMmbed/mbed-os-5-docs/issues)" and pressed the [New issue ](https://github.com/ARMmbed/mbed-os-5-docs/issues/new) button.   If the formatting of the issue doesn't meet your expectations, perhaps you should add instructions to the issue template.

**Comment by 0xc0170** [comment]
Hi, @ciarmcom is auto bot checking the issue template and mirroring issues to internal tracker.

RTX should be added to glossary. Taken from the official RTX page:

> Keil RTX5 is a royalty-free, deterministic, full-featured real-time operating system implementing the CMSIS-RTOS API v2

**Comment by ChrisGooch-Arm** [comment]
This was fixed in 6.13 onward:

https://os.mbed.com/docs/mbed-os/v6.13/introduction/glossary.html
