### ISSUE TITLE
Mbed CLI2 Target Support

### ISSUE THREAD

**Issue by AGlass0fMilk** [ARMmbed/Handbook#1470]
# Docs issue template

## Page link
https://os.mbed.com/docs/mbed-os/v6.12/build-tools/use.html

## Expected to find...

All boards are supported by Cmake, is this not the case for CLI2?

https://forums.mbed.com/t/cmake-update-all-boards-are-supported-unittests-request-for-review/12918

## Found

> Currently, Mbed CLI 2 supports three boards: K64F, DISCO_L475VG_IOT01A and NRF52840_DK.

**Comment by ciarmcom** [comment]
@AGlass0fMilk This issue has an incomplete or old issue template.For future reference please use an up to date clone of the repository before raising issues. Many thanks.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-4217*

**Comment by 0xc0170** [comment]
All boards should be supported, I can send PR quickly now

**Comment by 0xc0170** [comment]
created https://github.com/ARMmbed/mbed-os-5-docs/pull/1471
