### ISSUE TITLE
Couldn't install Mbed Studio on Ubuntu 20.04

### ISSUE THREAD

**Issue by mianqi2016** [ARMmbed/Handbook#1487]
## Page link
https://os.mbed.com/docs/mbed-studio/current/installing/installing-mbed-studio.html

## Expected to find...
Installing start.

## Found
after I typed:"sudo ./M*.sh"
it was prompted:"Please do not use sudo"

while, if I didn’t use sudo, it would prompted:"permission denied"

and, I couldn’t manually created tmp folder.

**Comment by 0xc0170** [comment]
Duplicate https://forums.mbed.com/t/please-do-not-run-with-sudo/14764, I'll close this one.
