### ISSUE TITLE
Handbook/docs/getting_started/blinky_compiler.md#Compile and Install, Step 6 Incorrect

### ISSUE THREAD

**Issue by bmenchaca** [ARMmbed/Handbook#152]
For the blinky_compiler document, the Compile and Install section, step 6 says:
6.  The board installs the program and then runs it. You should see the LED blink.

For us, this required a reset before the program took effect; flashing does not reload the program.

**Comment by theotherjimmy** [comment]
Ah, yes. Let's change that to reflect reality!

**Comment by AnotherButler** [comment]
@bmenchaca Thanks for finding this. I've put up PR #155 and marked you as a reviewer. Please let me know if my updated wording is correct.

**Comment by AnotherButler** [comment]
Closing due to fix in PR #155

**Comment by AnotherButler** [comment]
Note: Please feel free to reopen this issue if it has not been resolved to your satisfaction.
