### ISSUE TITLE
Source for https://docs.mbed.com/docs/mbed-os-handbook/en/latest/dev_tools/cli/

### ISSUE THREAD

**Issue by bmenchaca** [ARMmbed/Handbook#153]
I cannot find the source against which to file issues for the Handbook, Dev Tools, CLI.  The closest I could find the documentation is here:
https://github.com/ARMmbed/Handbook/blob/5.4/docs/dev_tools/cli.md

Which refers to:
https://raw.githubusercontent.com/ARMmbed/mbed-cli/master/README.md%7D

Which says 404.

**Comment by AnotherButler** [comment]
This page is transcluded from this README: [https://github.com/ARMmbed/mbed-cli](https://github.com/ARMmbed/mbed-cli). When we restructure these docs and move them to the new engine, we should be able to avoid this type of confusing transclusion. In the meantime, please make any PRs for this page against the linked README.

**Comment by iriark01** [comment]
Can we close this?

**Comment by AnotherButler** [comment]
@bmenchaca Please feel free to reopen this if you feel it has not been resolved fully.
