### ISSUE TITLE
VSCode page missing

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/Handbook#159]
VSCode feature is now landed, but the page was removed from handbook.

Can we put it back?

@AnotherButler

**Comment by AnotherButler** [comment]
Oh, yeah. We took it off the YAML because it wasn't merged in the code yet. Has it since been merged?

**Comment by janjongboom** [comment]
Yes

**Comment by AnotherButler** [comment]
[This page](https://docs.mbed.com/docs/mbed-os-handbook/en/latest/debugging/vscode/) is now back online.

**Comment by AnotherButler** [comment]
I'm closing this because that page is back online. Please reopen it if this has not resolved the issue.
