### ISSUE TITLE
Handbook website and sources mismatch

### ISSUE THREAD

**Issue by bulislaw** [ARMmbed/Handbook#192]
Content in sources and rendered website differ, it's not due to recent chances to docs, as the docs are quite old.
https://github.com/ARMmbed/Handbook/blob/5.5/docs/dev_tools/build_profiles.md
https://docs.mbed.com/docs/mbed-os-handbook/en/latest/dev_tools/build_profiles/

This part is missing from the website:
```
  * Debugger is likely to drop connection.
  * Breaks the local file system on the [mbed interface](https://docs.mbed.com/docs/mbed-os-handbook/en/latest/getting_started/mbed_interface/) on some boards.
```
for both develop and release profiles.

@AnotherButler

**Comment by AnotherButler** [comment]
@bulislaw Great eye. I have updated this. Is it OK to close?

**Comment by bulislaw** [comment]
Brilliant, thanks. Closing.
