### ISSUE TITLE
Where are the 5.6 Documentation sources?

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/Handbook#274]
Just noticed 5.6 documentation went live but I can't find sources to create an issue against.

**Comment by AnotherButler** [comment]
The sources are in the new_engine branch. We expect the branch to be renamed to 5.6 soon. Please let us know if there are more specific locations for which you're looking.

**Comment by AnotherButler** [comment]
Please don't hesitate to reopen this issue if you feel it has not been resolved.

**Comment by loverdeg-ep** [comment]
@AnotherButler As long as https://os.mbed.com/docs/v5.6 is live I'd prefer to leave it open for others until new_engine is re-labeled as 5.6

**Comment by loverdeg-ep** [comment]
@AnotherButler  I don't seem to have the option to re-open
