### ISSUE TITLE
ARM mbed OS software design guide location

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/Handbook#280]
[ARM Mbed OS Software Design Guide](https://os.mbed.com/docs/v5.6/tutorials/memory-optimization.html#arm-mbed-os-software-design-guide)
is generated as a subheading of: [Memory Optimization](https://os.mbed.com/docs/v5.6/tutorials/memory-optimization.html)

Should it be it's own, or on a different page?

**Comment by AnotherButler** [comment]
@loverdeg-ep Greate eye. Thanks for the issue.

Please let us know if this has been solved to your satisfaction, so we can close this issue.
