### ISSUE TITLE
Dead Links under Reference->Contributing->Connectivity

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/Handbook#283]
On the Reference Manual's  [Contributing](https://os.mbed.com/docs/v5.6/reference/contributing-connectivity.html) page the following links are dead.

[WiFiInterface.h](https://github.com/ARMmbed/mbed-os/blob/master/features/NetworkSocketAPI/WiFiInterface.h)

[CellularInterface.h](https://github.com/ARMmbed/mbed-os/blob/master/features/NetworkSocketAPI/CellularInterface.h)

[MeshInterface.h](https://github.com/ARMmbed/mbed-os/blob/master/features/NetworkSocketAPI/MeshInterface.h)

**Comment by AnotherButler** [comment]
@loverdeg-ep Great eye. Thanks for raising the issue. We have now addressed this. Please let us know if we can close this issue.
