### ISSUE TITLE
Need to elaborate on export-able toolchains?

### ISSUE THREAD

**Issue by andrewc-arm** [ARMmbed/Handbook#331]
Hi,

https://os.mbed.com/docs/v5.6/tutorials/eclipse.html
> This document explains how to build and debug Arm Mbed OS applications using Eclipse. Before starting, please configure your local debug toolchain.

The above text should be elaborated like following.
> This document explains how to build and debug Arm Mbed OS applications using Eclipse. Before starting, please check which debug toolchains you are targeting from this list.

Or maybe I am not understanding the intention well. Please elaborate.

**Comment by theotherjimmy** [comment]
Also, It looks like you tried to use asciidoc in your comment, when github only supports markdown.

**Comment by andrewc-arm** [comment]
OK. Thanks. That part of the text made me to read exportation page for long which was not needed. Please improve.

**Comment by AnotherButler** [comment]
I'm closing this because PR #373 resolves this. Please feel free to reopen this issue if you feel it is not resolved.
