### ISSUE TITLE
BLE class reference gives page error in v5.6 docs

### ISSUE THREAD

**Issue by senthilr** [ARMmbed/Handbook#362]
Clicking on the BLE Class Reference url throws "Page error" and the class reference does not render.
https://os.mbed.com/docs/v5.6/mbed-os-api-doxy/class_b_l_e.html
This seems to be the case for all BLE APIs
https://os.mbed.com/docs/v5.6/mbed-os-api-doxy/class_heart_rate_service.html
https://os.mbed.com/docs/v5.6/reference/ibeacon.html#ibeacon-class-reference
@AnotherButler

**Comment by AnotherButler** [comment]
@senthilr Thanks for raising this issue. Because of an mbed-os policy to exclude Doxygen that throws warnings, these APIs were not included in the 5.6 Doxygen. However, we have fixed this issue in 5.7: https://os.mbed.com/docs/v5.7/reference/ble.html

**Comment by AnotherButler** [comment]
Please don't hesitate to reopen this issue if you feel it is not resolved.
