### ISSUE TITLE
Serial - example three - printf in ISR

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/Handbook#375]
Reference: https://github.com/ARMmbed/Handbook/blob/5.7/docs/reference/api/drivers/Serial.md#example-three

It should either be doing buffering in ISR or use RawSerial (the api is regarding Serial thus would probably need to be rewritten to capture characters and process them in the main thread?)

**Comment by AnotherButler** [comment]
If this is incorrect, please update this example or let me know who to tag to do it.

**Comment by 0xc0170** [comment]
Done, Pr created : https://os.mbed.com/teams/mbed_example/code/Serial_ex_3/pull-request/1

@sarahmarshy can you review (I noticed your last commit there)

**Comment by sarahmarshy** [comment]
@0xc0170, my last commit just updated Mbed OS. Your changes Lgtm

**Comment by 0xc0170** [comment]
The example was updated, we just need now to point docs to this revision: https://os.mbed.com/teams/mbed_example/code/Serial_ex_3/rev/4ab47f33a1ae/

**Comment by 0xc0170** [comment]
Proposed fix referenced above, please review

**Comment by AnotherButler** [comment]
@0xc0170 Thank you for PRs. I have merged them and made the changes live, so I am closing this issue. Please feel free to reopen it if it is not resolved to your satisfaction.
