### ISSUE TITLE
Navigation Panel - Current Page Indicator too light

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/Handbook#379]
In the image below, I couldn't see the current page indication "light gray-blue highlight".

Looking at this on a different monitor indicated my monitor needed adjusting.

However, I still think the current page indication is either too light or needs a different indicator altogether.

![image](https://user-images.githubusercontent.com/24318071/35339242-14ce7e02-00ee-11e8-98a8-d7b988dce14c.png)

**Comment by AnotherButler** [comment]
@loverdeg-ep Thank you for your feedback. We appreciate your taking the time to let us know about this. I am passing this information on to our UX team.

**Comment by AnotherButler** [comment]
@loverdeg-ep I have spoken with our UX team. They say there are planned usability improvements that are related to our table of contents navigation, and they have added this as something to look into. Thank you again for raising this issue.
