### ISSUE TITLE
Inconsistent Page Leveling

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/Handbook#380]
The following screen capture comes from the page shown when I select [Reference](https://os.mbed.com/docs/v5.7/reference/index.html) in the navigation pane.

![image](https://user-images.githubusercontent.com/24318071/35342172-647e57cc-00f5-11e8-94e3-37c1c0517273.png)

As shown selecting [Reference](https://os.mbed.com/docs/v5.7/reference/index.html) actually takes you down 2 extra levels to the "MBED OS Reference Book" page.

All other top level Navigation links (Introduction, Tools, Tutorials) behave similarly.

Compare this behavior to when [Configuration](https://os.mbed.com/docs/v5.7/reference/configuration.html) is selected.

![image](https://user-images.githubusercontent.com/24318071/35342304-bd5be224-00f5-11e8-830e-d24205a3d3f9.png)

I would greatly prefer the behavior exhibited in the latter example for the top level navigation links.

Let me know if this is confusing.

**Comment by loverdeg-ep** [comment]
@AnotherButler Does this follow under the "planned usability improvements that are related to our table of contents navigation" from #379?

If so please close.

**Comment by AnotherButler** [comment]
@loverdeg-ep Yes, this does. I think there may be a temporary workaround I can do from my end in the meantime. I'm going to leave this ticket open while I explore this option, but if it doesn't work, we'll have to wait for the planned improvements.

**Comment by AnotherButler** [comment]
Closing until planned usability improvements are complete

**Comment by AnotherButler** [comment]
@loverdeg-ep Our UX team says we can expect to see changes in June.
