### ISSUE TITLE
Recommended procedure for testing

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/Handbook#391]
From what I recall the doc pages are rendered with an ARM proprietary system.
If I wanted to make changes to the docs how would you recommend I test?

Would be nice to have CI going for this repository...

**Comment by AnotherButler** [comment]
We recommend contributors add and update content to our documentation the same way they do to Mbed OS, by putting up a PR. We review all PRs on our internal testing site.

We also have an open PR in progress to validate code snippets: https://github.com/ARMmbed/Handbook/pull/246
