### ISSUE TITLE
Enable CI/CD for Public Handbook Repository

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/Handbook#407]
Any chance of this happening? 

What is preventing if not?

**Comment by AnotherButler** [comment]
@loverdeg-ep There is a [PR in progress](https://github.com/ARMmbed/Handbook/pull/246) to enable Travis validation of code snippets. Is this what you had in mind?

**Comment by loverdeg-ep** [comment]
@AnotherButler Not sure why I opened this in the first place actually.

I guess I was thinking more along the lines of giving community members the ability to generate the documentation themselves to validate any PR's they might make.

Feel free to close or ignore till I de-tangle my brain.
