### ISSUE TITLE
mbed CLI for Windows download link is a code block

### ISSUE THREAD

**Issue by vergil-SI** [ARMmbed/Handbook#412]
The download link for mbed CLI for Windows is extremely difficult to find due to it being a code block

https://os.mbed.com/docs/v5.7/tools/installing-with-the-windows-installer.html

It took me and 2 others over 5 minutes to realize that "mbed-windows-installer v0.4.3" was a link and not a command for the CLI.

**Comment by AnotherButler** [comment]
@vergil-SI Thanks for raising this issue. That's a great observation. We have removed the code formatting, so the link is now more visible. Please feel free to reopen this issue if you feel this has not been resolved.
