### ISSUE TITLE
Dead Link on Docs › Reference › Guidelines › Workflow

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/Handbook#511]
https://os.mbed.com/docs/v5.8/reference/workflow.html
https://os.mbed.com/docs/v5.8/reference/how-we-release-arm-mbed-os.html <- dead

![image](https://user-images.githubusercontent.com/24318071/39647170-d914dd22-4fab-11e8-8f3c-8a3f67ceacd1.png)

**Comment by AnotherButler** [comment]
@loverdeg-ep Great catch. Thanks. I've fixed this now.
