### ISSUE TITLE
Mbed statistics page: cannot access examples

### ISSUE THREAD

**Issue by chuanga** [ARMmbed/Handbook#558]
Reviewed MbedStats.md page (https://github.com/deepikabhavnani/Handbook/blob/2324689b7a5f20fa494995178e3fd787b5f86b57/docs/reference/api/platform/MbedStats.md) as part of Mbed 5.9 OOB

Showing "Access Denied" Error when I clicked on the bottom 4 examples (Thread statistics, System Info, CPU statistics, CPU usage).

**Comment by iriark01** [comment]
Handled with #553
