### ISSUE TITLE
Bootloader tutorial should explain application header 

### ISSUE THREAD

**Issue by chuanga** [ARMmbed/Handbook#559]
Review bootloader.md page (https://github.com/ARMmbed/Handbook/blob/5.8/docs/tutorials/bootloader.md) as part of mbed-os-5.9). Cannot access master branch; so look at 5.8 branch instead.

Document should explain fields of application header or have a link to relevant document if available.

**Comment by AnotherButler** [comment]
You should be reviewing 5.9 documents on our staging site, which requires being on the network. Please see this page: https://os-doc-builder.test.mbed.com/docs/development/tutorials/bootloader.html

**Comment by AnotherButler** [comment]
To raise a PR against the correct branch, please use the new_engine branch. This goes to our staging site. We do not work on master.

**Comment by AnotherButler** [comment]
We exposed the link to relevant documentation. Is it OK to close this issue?

**Comment by MarceloSalazar** [comment]
Closing. @chuanga please reopen if you see an issue.
