### ISSUE TITLE
Minor issues on Error Handling

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/Handbook#580]
The Error Handling doc is really good :)

Find here feedback on minor issues that would be nice to improve.

>MBED_ERROR vs MBED_ERROR1 (and MBED_WARNING vs MBED_WARNING1)

The doc is referring to these functions many times, and I couldn't find the answer in this doc.
As a user, I'd like to understand the differences early. Few suggestions.
- Add "see API (link TBA) for more information"
- Optionally add: MBED_ERROR takes status and message. MBED_ERROR1 takes an additional context-specific argument (see API for more information)

> Intro: "Error status types and error code ranges"
> ...
- System errors. --> It seems this involves many items below, but I'm unsure which one(s), maybe list them here and add links to the sections below?
- Posix errors.  --> it's somehow clear because the content comes early in doc, but can we add link to "Posix error codes support" ?
- Custom defined errors. --> Can we add a link to "Extending error codes" section below?

> MODULE_APPLCIATION --> MODULE_APPLICATION

Minor typo.

@AnotherButler 
cc @SenRamakri

**Comment by SenRamakri** [comment]
PR created with fixes - https://github.com/ARMmbed/Handbook/pull/586

**Comment by AnotherButler** [comment]
Closing because PR #586 merged. Please feel free to reopen if you do not feel this is resolved.
