### ISSUE TITLE
Formatting of Adding And Configuring Targets Page

### ISSUE THREAD

**Issue by 0Grit** [ARMmbed/Handbook#904]
# Docs issue template

## Page link
https://os.mbed.com/docs/v5.11/reference/adding-and-configuring-targets.html

## Expected to find...
Awesome content and decent formatting
## Found
better than awesome content but, tons of formatting issues

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-871*

**Comment by AnotherButler** [comment]
@loverdeg-ep Thanks for raising this issue. Could you please be more specific about the formatting issues you see? Also, could you please tell us which browser you're using?

**Comment by 0Grit** [comment]
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/24318071/50977109-8d184d80-14bf-11e9-8fc2-5ccc4919cc0d.png)


![image](https://user-images.githubusercontent.com/24318071/50977062-6d812500-14bf-11e9-8724-150d3ebe2721.png)


![image](https://user-images.githubusercontent.com/24318071/50977091-7a057d80-14bf-11e9-8d15-472ddf54ba6b.png)

**Comment by 0Grit** [comment]
@AnotherButler The section heading are formatted in a way that makes it hard for me to scan through a document. I ended up blowing through sections without realizing I skipped them or that they existed.

This seems to be a trend on a lot of other pages too. I can document some of them when I get time.

**Comment by AnotherButler** [comment]
@loverdeg-ep Thanks for the details. I see what you mean. We'll schedule this to fix it. Thanks for raising this issue 👍

**Comment by AnotherButler** [comment]
We've updated the formatting of the headings on the relevant pages. Does this solve this issue?

**Comment by 0Grit** [comment]
Much better but something is still off.

![image](https://user-images.githubusercontent.com/24318071/51329471-8ea7bf80-1a43-11e9-9e86-fe3f55c52fa6.png)


Might be the spacing between sections?

**Comment by AnotherButler** [comment]
Unfortunately, I can't change the spacing between lines to the level of detail. I can pass the feedback on to our UX team, though. There's a chance they can do something on the back end.

**Comment by 0Grit** [comment]
@AnotherButler 
Yeah I think more spacing before the section header, less spacing after section header would do the trick.
Looks like almost a full line of space after the section header.

**Comment by AnotherButler** [comment]
@loverdeg-ep I've alerted our UX team members, so they can perform an analysis on this request. If they move forward with it, once I learn of a delivery date, I'll reopen this issue with that information.
