### ISSUE TITLE
Error: Undefined symbol dot (referred from ../../build/examples/src/dot_util.MTS_MDOT_F411RE.o).

### ISSUE THREAD

**Issue by dongxusong** [ARMmbed/Handbook#932]
I can't compile, The error information is:

Error: Undefined symbol dot (referred from ../../build/examples/src/dot_util.MTS_MDOT_F411RE.o).

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-905*

**Comment by adbridge** [comment]
@dongxusong Please provide more details. There is insufficient details here for us to even investigate. What are you compiling? What compiler? What version of mbed-os etc? Also this should really be raised in the mbed-os repository - could you please open a more comprehensive issue there and close this one? Thanks

**Comment by AnotherButler** [comment]
I'm closing this issue because we can't resolve it without more information. Please feel free to reopen it with answers to the questions from @adbridge
