### ISSUE TITLE
Ambiguous description of how the network interface behaves for 6LoWPAN networks

### ISSUE THREAD

**Issue by 0Grit** [ARMmbed/Handbook#936]
# Docs issue template

## Page link
https://os.mbed.com/docs/mbed-os/v5.11/apis/network-interfaces.html
## Expected to find...

Not sure

## Found
Ambiguous description of how the network interface behaves for 6lowpan networks.
![image](https://user-images.githubusercontent.com/24318071/52175650-c5d0dd00-2774-11e9-9322-3719699e39f5.png)

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-908*

**Comment by AnotherButler** [comment]
@SeppoTakalo Could you please help with this?

**Comment by SeppoTakalo** [comment]
Yes, assign then internal ticket to my team.

**Comment by SeppoTakalo** [comment]
Will be fixed in https://github.com/ARMmbed/mbed-os-5-docs/pull/957
