### ISSUE TITLE
Add this repository to ARMmbed pinned repo's

### ISSUE THREAD

**Issue by 0Grit** [ARMmbed/Handbook#942]
# Docs issue template

## Page link

https://github.com/ARMmbed

## Would like to find...

mbed-os-5-docs pinned at top. I've got a bookmark but...

## Found

![image](https://user-images.githubusercontent.com/24318071/52378377-7f5dd580-2a35-11e9-914a-9e9c3c081710.png)

**Comment by AnotherButler** [comment]
I think this is a great suggestion. @ARMmbed/mbed-os-maintainers What are your thoughts? Is this something we can do?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-916*

**Comment by 0Grit** [comment]
@adbridge Can this be adjusted?
@ARMmbed/mbed-os-maintainers 

People probably look for the docs more than they do minimal-printf

![image](https://user-images.githubusercontent.com/24318071/62626522-9488c380-b8f5-11e9-8c60-64072eca1528.png)

**Comment by evedon** [comment]
It's my bad I think! 
I changed that recently thinking these repos were pinned for me only... ! 
I will revert to the ones shown at the top, plus the mbed-os-5-docs

**Comment by 0Grit** [comment]
Hahha, NP. I had a feeling somebody changed them thinking they were per user.
