### ISSUE TITLE
Circular Link

### ISSUE THREAD

**Issue by 0Grit** [ARMmbed/Handbook#946]
# Docs issue template

## Page link

https://os.mbed.com/docs/mbed-os/v5.11/contributing/index.html#licensing

The contributing guidelines link, links to the section it is contained within.

![image](https://user-images.githubusercontent.com/24318071/52483114-197e6480-2b81-11e9-817e-9a89686fe042.png)

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-918*

**Comment by AnotherButler** [comment]
Thanks for raising this issue 👍 This has now been resolved, which you can see at the link.

**Comment by 0Grit** [comment]
This is resolved. But I found something else upon clicking the link.
