### ISSUE TITLE
Link broken in advanced/mbed_targets page.

### ISSUE THREAD

**Issue by fredlee12001** [ARMmbed/Handbook#95]
At the end of the [advanced/mbed_targets](https://docs.mbed.com/docs/mbed-os-handbook/en/5.3/advanced/mbed_targets/#device_name) page, there is a link to exporter. 
It links to [https://docs.mbed.com/docs/mbed-os-handbook/en/5.3/advanced/mbed_targets/exporters.md](https://docs.mbed.com/docs/mbed-os-handbook/en/5.3/advanced/mbed_targets/exporters.md).

While this link seems to be broken, we got 404 error for that link.

**Comment by iriark01** [comment]
I've rebuilt the handbook if you want to check this

**Comment by AnotherButler** [comment]
The updated Handbook looks good to me. @fredlee12001 Does this look good to you? Can we close this issue?

**Comment by iriark01** [comment]
I think we should close it
