### ISSUE TITLE
Bad text contrast for LICENSE file snippet

### ISSUE THREAD

**Issue by 0Grit** [ARMmbed/Handbook#950]
# Docs issue template

## Page link
https://os.mbed.com/docs/mbed-os/v5.11/contributing/license.html

Chrome Version 71.0.3578.98 (Official Build) (64-bit)

## Expected to find...
Mostly readable license text.
## Found
![image](https://user-images.githubusercontent.com/24318071/52716874-be2be800-2f6d-11e9-99e0-708be6c7dcdc.png)

**Comment by 0xc0170** [comment]
Good find, I noticed this as well !

**Comment by AnotherButler** [comment]
Thanks for raising this issue, @loverdeg-ep 👍 

I have updated the snippet formatting. Please feel free to reopen this issue if this fix does not resolve it.
