### ISSUE TITLE
We have one issue with low power state on U-Blox C030-U201 when we are using the latest mbed-os the board won't enter on deep sleep. This issue is not happening with release version:  3823:2b4ff78

### ISSUE THREAD

**Issue by nusret103** [ARMmbed/Handbook#993]
# Docs issue template

**Comment by nusret103** [comment]
We have one issue with low power state on U-Blox C030-U201 when we are using the latest mbed-os the board won't enter on deep sleep. This issue is not happening with release version:

3823:2b4ff78

**Comment by 0xc0170** [comment]
Please add this to Mbed OS repository. I'll close this one.

We will need more details - how to reproduce the issue.
