### ISSUE TITLE
FSB usage missing from LoRaWAN documentation

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/Handbook#996]
We have the [FSB_Usage](https://github.com/ARMmbed/mbed-os/blob/master/features/lorawan/FSB_Usage.txt) document that lives in the `lorawan` feature in Mbed OS, but this document is not in the docs. It's very useful and it should be integrated in the LoRaWAN documentation.

cc @hasnainvirk

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTDOCS-961*

**Comment by AnotherButler** [comment]
Because this does not fit into our planned documentation at this time, we have no plans to resolve this issue in the near future. Therefore, I'm going to close this issue.
